In [ ]:
import numpy as np
from scipy.optimize import minimize, least_squares

## Part a

Looks like my first theta value is accurate, however my other theta values are slightly off (Not sure why this is happening, I tried several initial values). This changed my FIM slightly however you can see the same trends in the array (which entries are largest/smallest, positive/negative). Similarly my eigenvalues are similar to the solution eigenvalues.

In [70]:

u_vals = [4,2,1,0.5,0.25,0.167,0.1,0.0833,0.0714,0.0625]
b = [0.1957, 0.1947, 0.1735, 0.16, 0.0844, 0.0627, 0.0456, 0.0342, 0.0323, 0.0235, 0.0246]
b = np.array(b)
y = lambda theta, u : (theta[0]*(u**2 + theta[1]*u))/(u**2 + theta[2]*u + theta[3])

def y(theta,u):
    theta = np.abs(np.log(theta))
    return (theta[0]*(u**2 + theta[1]*u))/(u**2 + theta[2]*u + theta[3])

def cost(theta):
    out = [y(theta,u_vals[k]) - b[k] for k in range(len(u_vals))]
    return np.array(out)

theta_0 = [0.1,0.1,0.1,0.1]
v = least_squares(cost, theta_0, method="lm")
theta = v["x"]
print("Cost: " + str(np.linalg.norm(cost(theta),2)) + " ---- Theta: " + str(np.abs(np.log(theta))))

Cost: 0.019829802326365144 ---- Theta: [0.19178242 0.35075642 0.24187715 0.18232914]


In [82]:
def jacob(theta):
    theta = np.abs(np.log(theta))
    c1 = [(u**2 + theta[1]*u)/(u**2 + theta[2]*u + theta[3]) for u in u_vals]
    c2 = [theta[0]*u/(u**2 + theta[2]*u + theta[3]) for u in u_vals]
    c3 = [-u*(theta[0]*(u**2 + theta[1]*u))/(u**2 + theta[2]*u + theta[3])**2  for u in u_vals]
    c4 = [-(theta[0]*(u**2 + theta[1]*u))/(u**2 + theta[2]*u + theta[3])**2  for u in u_vals]
    return np.column_stack([c1,c2,c3,c4])


def FIM(theta):
    j = jacob(theta)
    return (j.T @ j)/10

F = FIM([0.197, 0.3508, 0.2419, 0.1823])

print(F)
print("Eigenvalues: ", np.linalg.eigvals(F))

[[ 0.1630447   0.08539002 -0.05308374 -0.03331393]
 [ 0.08539002  0.05467136 -0.02829186 -0.0246562 ]
 [-0.05308374 -0.02829186  0.01786713  0.01106625]
 [-0.03331393 -0.0246562   0.01106625  0.01207184]]
Eigenvalues:  [2.35370190e-01 1.17491399e-02 5.29790301e-04 5.91576306e-06]
